// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  authDomain: "portfolio-3066d.firebaseapp.com",
  apiKey: "AIzaSyBx84z8W11vQNjOnnfiGePP3H9aODaA9Sc",
  projectId: "portfolio-3066d",
  storageBucket: "portfolio-3066d.appspot.com",
  messagingSenderId: "841904913683",
  appId: "1:841904913683:web:fab57f80668ed18c06eee6",
  measurementId: "G-CJVLNBRJJ9"
  );

  static const FirebaseOptions android = FirebaseOptions(
  apiKey: "AIzaSyBx84z8W11vQNjOnnfiGePP3H9aODaA9Sc",
  projectId: "portfolio-3066d",
  storageBucket: "portfolio-3066d.appspot.com",
  messagingSenderId: "841904913683",
  appId: "1:841904913683:web:fab57f80668ed18c06eee6",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBx84z8W11vQNjOnnfiGePP3H9aODaA9Sc",
  projectId: "portfolio-3066d",
  storageBucket: "portfolio-3066d.appspot.com",
  messagingSenderId: "841904913683",
  appId: "1:841904913683:web:fab57f80668ed18c06eee6",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyBx84z8W11vQNjOnnfiGePP3H9aODaA9Sc",
  projectId: "portfolio-3066d",
  storageBucket: "portfolio-3066d.appspot.com",
  messagingSenderId: "841904913683",
  appId: "1:841904913683:web:fab57f80668ed18c06eee6",
  );
}
